# Generated by Django 4.0.4 on 2022-06-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photography',
            new_name='Content',
        ),
    ]
