# Generated by Django 4.0.4 on 2022-06-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_photography_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Photography',
        ),
        migrations.AddField(
            model_name='content',
            name='content',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_img', to='posts.image'),
        ),
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='image',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, max_length=255, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.content')),
            ],
        ),
    ]
