# Generated by Django 4.0.4 on 2022-06-12 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_image_photography_content_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='photo',
        ),
        migrations.AddField(
            model_name='image',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_img', to='posts.content'),
        ),
    ]
