# Generated by Django 4.0.4 on 2022-06-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_content_photo_image_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='photo',
            new_name='post_linked',
        ),
    ]
