# Generated by Django 4.0.3 on 2022-06-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_photo_image_post_linked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(choices=[('flora', 'Flora'), ('beach', 'Beach'), ('art', 'Art'), ('poetry', 'Poetry')], max_length=128),
        ),
    ]
