# Generated by Django 4.0.4 on 2022-06-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_content_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='media/img'),
        ),
    ]
