# Generated by Django 4.0.4 on 2022-06-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_content_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(choices=[('playas del Coco', 'Playas del Coco'), ('playa ocotal', 'Playa Ocotal'), ('playa hermosa', 'Playa Hermosa'), ('marino ballena', 'Marino Ballena')], max_length=128),
        ),
    ]
