# Generated by Django 4.0.3 on 2022-06-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/img')),
                ('username', models.CharField(max_length=75)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('about', models.CharField(blank=True, max_length=400)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
